# Generated by Django 5.2.5 on 2025-08-20 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_options_alter_blogs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdfs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
